FROM python:3.12-slim

WORKDIR /src

RUN pip install poetry

COPY ./src /src/

WORKDIR /src

RUN poetry install

EXPOSE 8501

CMD ["poetry", "run", "streamlit", "run", "dataApp/streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
